import { gameFrame } from './shared.js'

export function buildMarioHtml() {
  const body = `<canvas id="c" width="560" height="300"></canvas><div class="row"><button class="btn" id="left">IZQUIERDA</button><button class="btn" id="jump">SALTAR</button><button class="btn" id="right">DERECHA</button></div><div class="hint">Avanza, recoge monedas y llega a la bandera. Puedes saltar sobre los enemigos.</div>`
  const script = `
var c=document.getElementById('c'),x=c.getContext('2d'),stat=document.getElementById('stat'),W=c.width,H=c.height;
var p,keys,platforms,coins,enemies,cam,score,lives,goal,state;
function reset(){p={x:35,y:210,w:24,h:32,vx:0,vy:0,on:false};keys={l:false,r:false};platforms=[{x:0,y:260,w:2300,h:40},{x:220,y:205,w:105,h:14},{x:420,y:170,w:110,h:14},{x:650,y:210,w:100,h:14},{x:860,y:160,w:120,h:14},{x:1090,y:205,w:110,h:14},{x:1350,y:165,w:120,h:14},{x:1610,y:210,w:120,h:14},{x:1880,y:165,w:130,h:14}];coins=[];for(var i=130;i<2100;i+=115)coins.push({x:i,y:i%230===0?130:220,t:false});enemies=[];for(var j=330;j<2050;j+=300)enemies.push({x:j,y:236,w:24,h:24,v:-1,a:true,min:j-80,max:j+80});cam=0;score=0;lives=3;goal=2160;state='play';stat.textContent='PUNTOS 0 · VIDAS 3'}
function jump(){if(state!=='play'){reset();return}if(p.on){p.vy=-11.5;p.on=false}}
function collide(a,b){return a.x+a.w>b.x&&a.x<b.x+b.w&&a.y+a.h>b.y&&a.y<b.y+b.h}
function die(){lives--;if(lives<=0){state='dead'}else{p.x=Math.max(35,cam+45);p.y=170;p.vx=0;p.vy=0}stat.textContent='PUNTOS '+score+' · VIDAS '+lives}
function update(){if(state!=='play')return;if(keys.l)p.vx=-3.8;else if(keys.r)p.vx=3.8;else p.vx*=.78;p.x+=p.vx;if(p.x<0)p.x=0;p.vy+=.58;p.y+=p.vy;p.on=false;for(var i=0;i<platforms.length;i++){var q=platforms[i];if(p.x+p.w>q.x&&p.x<q.x+q.w&&p.y+p.h>=q.y&&p.y+p.h-p.vy<=q.y+8){p.y=q.y-p.h;p.vy=0;p.on=true}}for(var k=0;k<coins.length;k++){var co=coins[k];if(!co.t&&Math.abs((p.x+12)-co.x)<18&&Math.abs((p.y+14)-co.y)<24){co.t=true;score+=100}}for(var e=0;e<enemies.length;e++){var en=enemies[e];if(!en.a)continue;en.x+=en.v;if(en.x<en.min||en.x>en.max)en.v*=-1;if(collide(p,en)){if(p.vy>0&&p.y+p.h-p.vy<=en.y+8){en.a=false;p.vy=-7;score+=200}else die()}}if(p.y>H+30)die();cam+=(Math.max(0,p.x-120)-cam)*.12;if(p.x>=goal){score+=1000;state='win'}stat.textContent='PUNTOS '+score+' · VIDAS '+lives}
function drawPlayer(px){x.fillStyle='#ef4444';x.fillRect(px+3,p.y,18,8);x.fillStyle='#f5c48a';x.fillRect(px+6,p.y+8,15,9);x.fillStyle='#2563eb';x.fillRect(px+4,p.y+17,17,13);x.fillStyle='#78350f';x.fillRect(px+3,p.y+29,8,3);x.fillRect(px+15,p.y+29,8,3)}
function draw(){x.fillStyle='#67b7ff';x.fillRect(0,0,W,H);x.fillStyle='#fff';for(var cl=0;cl<7;cl++){var cx=(cl*130-(cam*.18)%130);x.beginPath();x.arc(cx,55+(cl%2)*26,18,0,7);x.fill()}x.save();x.translate(-cam,0);for(var i=0;i<platforms.length;i++){var q=platforms[i];x.fillStyle=q.y===260?'#7c4a22':'#c08457';x.fillRect(q.x,q.y,q.w,q.h);x.fillStyle='#22c55e';x.fillRect(q.x,q.y,q.w,4)}for(var k=0;k<coins.length;k++){var co=coins[k];if(co.t)continue;x.fillStyle='#facc15';x.beginPath();x.arc(co.x,co.y,7,0,7);x.fill()}for(var e=0;e<enemies.length;e++){var en=enemies[e];if(!en.a)continue;x.fillStyle='#7c2d12';x.fillRect(en.x,en.y,en.w,en.h);x.fillStyle='#fff';x.fillRect(en.x+5,en.y+5,4,4);x.fillRect(en.x+15,en.y+5,4,4)}x.fillStyle='#e2e8f0';x.fillRect(goal,95,5,165);x.fillStyle='#22c55e';x.fillRect(goal+5,100,46,28);drawPlayer(p.x-cam+cam);x.restore();if(state!=='play'){x.fillStyle='rgba(2,6,23,.75)';x.fillRect(0,0,W,H);x.textAlign='center';x.fillStyle='#fff';x.font='900 27px Arial';x.fillText(state==='win'?'NIVEL COMPLETADO':'GAME OVER',W/2,125);x.font='700 13px Arial';x.fillText('Pulsa SALTAR para reiniciar',W/2,155);x.textAlign='left'}}
function hold(id,key){var b=document.getElementById(id);b.onpointerdown=function(e){e.preventDefault();keys[key]=true};['pointerup','pointercancel','pointerleave'].forEach(function(n){b.addEventListener(n,function(){keys[key]=false})})}hold('left','l');hold('right','r');document.getElementById('jump').onpointerdown=function(e){e.preventDefault();jump()};function loop(){update();draw();requestAnimationFrame(loop)}reset();loop();`
  return gameFrame('MINI MARIO', 'PLATAFORMAS TÁCTILES', body, script)
}
